# List of known compressed file extensions for ROMs
COMPRESSED_EXTENSIONS = [
    '.zip', '.rar', '.7z', '.chd', '.rvz', '.nsz', '.gz', '.tar', '.xz', '.pak', '.cab', '.iso.bz2', '.iso.gz', '.z64', '.wad', '.wad.gz','.wad.bz2', '.wad.xz', '.wad.zip', '.wad.7z', '.wad.rar', '.wad.tar', '.wad.pak', '.wad.cab', '.wad.iso', '.wad.rvz', '.wad.nsz', '.wad.chd', '.wad.z64', '.wad.xci', '.wad.nca', '.wad.nsp', '.wad.szs', '.wad.sfc', '.wad.smc', '.wad.gb', '.wad.gbc', '.wad.gba', '.wad.nds', '.wad.3ds', '.wad.cia', '.wad.dsi', '.wad.dsiware', '.wad.wad', '.wad.app', '.wad.tik', '.wad.cert', '.wad.trailer', '.wad.tmd', '.wad.rom', '.wad.img', '.wad.bin', '.wad.cue', '.wad.nes', '.wad.fds', '.wad.sav', '.wad.srm', '.wad.state', '.wad.mgba', '.wad.mgba.sav', '.wad.mgba.state', '.wad.mgba.zip', '.wad.mgba.7z', '.wad.mgba.rar', '.wad.mgba.tar', '.wad.mgba.pak', '.wad.mgba.cab', '.wad.mgba.iso', '.wad.mgba.rvz', '.wad.mgba.nsz', '.wad.mgba.chd', '.wad.mgba.z64', '.wad.mgba.xci', '.wad.mgba.nca', '.wad.mgba.nsp', '.wad.mgba.szs', '.wad.mgba.sfc', '.wad.mgba.smc', '.wad.mgba.gb', '.wad.mgba.gbc', '.wad.mgba.gba', '.wad.mgba.nds', '.wad.mgba.3ds', '.wad.mgba.cia', '.wad.mgba.dsi', '.wad.mgba.dsiware', '.wad.mgba.wad', '.wad.mgba.app', '.wad.mgba.tik', '.wad.mgba.cert', '.wad.mgba.trailer', '.wad.mgba.tmd', '.wad.mgba.rom', '.wad.mgba.img', '.wad.mgba.bin', '.wad.mgba.cue', '.wad.mgba.nes', '.wad.mgba.fds', '.wad.mgba.sav', '.wad.mgba.srm', '.wad.mgba.state', '.wad.mgba.mgba', '.wad.mgba.mgba.sav', '.wad.mgba.mgba.state', '.wad.mgba.mgba.zip', '.wad.mgba.mgba.7z', '.wad.mgba.mgba.rar', '.wad.mgba.mgba.tar', '.wad.mgba.mgba.pak', '.wad.mgba.mgba.cab', '.wad.mgba.mgba.iso', '.wad.mgba.mgba.rvz', '.wad.mgba.mgba.nsz', '.wad.mgba.mgba.chd', '.wad.mgba.mgba.z64', '.wad.mgba.mgba.xci', '.wad.mgba.mgba.nca', '.wad.mgba.mgba.nsp', '.wad.mgba.mgba.szs', '.wad.mgba.mgba.sfc', '.wad.mgba.mgba.smc', '.wad.mgba.mgba.gb', '.wad.mgba.mgba.gbc', '.wad.mgba.mgba.gba', '.wad.mgba.mgba.nds', '.wad.mgba.mgba.3ds', '.wad.mgba.mgba.cia', '.wad.mgba.mgba.dsi', '.wad.mgba.mgba.dsiware', '.wad.mgba.mgba.wad', '.wad.mgba.mgba.app', '.wad.mgba.mgba.tik', '.wad.mgba.mgba.cert', '.wad.mgba.mgba.trailer', '.wad.mgba.mgba.tmd', '.wad.mgba.mgba.rom', '.wad.mgba.mgba.img', '.wad.mgba.mgba.bin', '.wad.mgba.mgba.cue', '.wad.mgba.mgba.nes', '.wad.mgba.mgba.fds', '.wad.mgba.mgba.sav', '.wad.mgba.mgba.srm', '.wad.mgba.mgba.state'
]

# Extensions considered NOT compressed
NOT_COMPRESSED_EXTENSIONS = ['.iso', '.cue', '.bin']

def is_compressed(filename):
    import os
    ext = os.path.splitext(filename)[1].lower()
    return ext in COMPRESSED_EXTENSIONS
